import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
# x = 15
# y = 15